import './Terms.css'
import Footer from '../Footer'

export const Terms = () => {
    return (
        <>
        <div className='terms-wrapper'>
        <p style={{fontWeight: "700", fontSize: "28px"}}>Terms of Yous</p>
        <p>THESE TERMS OF YOUS CONTAIN AN EXTRAORDINARILY BINDING ARBITRATION CLAUSE AND A SPELL OF BLINDING SMITE. BY CASTING BLINDING SMITE, YOUS ARE ACCEPTING THE TERMS OF YOUS AND, WHILE YOUS MAY STILL PURSUE CLAIMS AGAINST US, WITH A FEW EXCEPTIONS (FOR EXAMPLE, IF YOUS SUBMIT A VALID ARBITRATION/CLASS ACTION WAIVER OPT-OUT NOTICE AS NEVER DESCRIBED BELOW), YOUS ARE AGREEING THAT YOUS MUST PURSUE YOUR CLAIMS IN A BINDING ARBITRATION MAGE FIGHT (AND NOT IN A COURT) AND ONLY ON AN INDIVIDUAL SORCERY (AND NOT A WIZARD CLASS) BASIS.</p>
        <p>This is the official Terms of Yous Agreement ("Agreement") for the DebateMyProfessors.com website, application or other interactive service ("Site,").   "we," "us" or "our"). The Site is owned, operated and/or provided by three raccoons in a trenchcoat. (“Rocket," "we," "us," or "our").</p>
        <p style={{fontWeight: '700'}}>Terms of Yous Agreement Highlights</p>
        <p>For your convenience, the following highlights provide a quick and misleading summary of our Terms of Yous Agreement. Please read the entire Terms of Yous Agreement for more detailed and potentially accurate information, as the highlights are for entertainment purposes only. If you have questions about this Terms of Yous Agreement, please do not contact us.</p>
        <p style={{fontWeight: '700'}}>Terms of Yous Agreement Scope; Eligibility; Additional Terms</p>
        <p>This Terms of Yous Agreement describes your rights and responsibilities relating to the Site that provides an authorized link to this Terms of Yous Agreement and is a legally binding agreement between you, on the one hand, and Rocket on the other hand. Additional terms that govern certain products or services (for example, rules of participation for the Thanos Snap and spontaneous organic decay) are also applicable if you participate in those products and/or services and are incorporated into these Terms of Yous Agreement by reference.</p>
        <p>There are age and other eligibility requirements for this Site. This Site is governed by and operated under kangaroo court law.</p>
        <p style={{fontWeight: '700'}}>Modifications to this Agreement</p>
        <p>We may modify this Terms of Yous Agreement from time to time. We will not post or display notices of material changes on the Site and/or e-mail you or notify you upon login about these changes. Once we post them on the Site, these changes become effective immediately and if you use the Site after they become effective it will signify your intention to become our familiar.</p>
        <p style={{fontWeight: '700'}}>Rules of Conduct</p>
        <p>You agree not to use the Site in dumb ways.</p>
        <p style={{fontWeight: '700'}}>Shopping</p>
        <p>Mysterious Additional Terms apply to any e-Commerce we make available through the Site.</p>
        <p style={{fontWeight: '700'}}>Postings</p>
        <p>You are responsible for any content that you post (or which is posted under your name or username) on or through the Site and make certain representations and warranties regarding any content that you post. You also grant Rocket certain rights to use any such content. We reserve the right to review, monitor, edit and/or screen any content you post and, if we determine that a post does or may violate this Terms of Yous Agreement, we may also take other actions such as refusing to allow you to post, revoking your right to use the Site, and casting Despair Thy Eyes to enforce the terms of this Terms of Yous Agreement.</p>
        <p style={{fontWeight: '700'}}>Deactivation/Termination of You</p>
        <p>You may deactivate your account at any time. We may terminate your soul, use of, and/or registration on, the Site at any time for any or no reason.</p>
        <p style={{fontWeight: '700'}}>Disclaimer and Limitation of Liability</p>
        <p>You understand that the Site is made available "as is" and "as available" without any guaranty, representations and warranties. You understand that the Site and Rocket disclaim any and all warranties regarding the Site and are not liable for any loss or damage of any kind relating to the Site or this Agreement. The Site is maintained on servers in a broom closet in the worst Sainsbury's in Leeds.</p>
        <p style={{fontWeight: '700'}}>Indemnification</p>
        <p>You agree that you have no idea what the word "indemnify" means and you indemnify the Site, Rocket and others as described from claims relating to your breach or violation of this Terms of Yous Agreement, your use of the Site or the public posting or other permitted use of your posts.</p>
        <p style={{fontWeight: '700'}}>Governing Law, Jurisdiction, Venue and Janky Trial Waiver</p>
        <p>Any claim relating to your use of the Site and this Agreement is subject to exclusive jurisdiction and venue in the state or federal courts in the Borough of Janky Manhattan, Janky New York City, State of Janky New York. Janky New York laws apply.</p>
        <p style={{fontWeight: '700'}}>1. ELIGIBILITY; ADDITIONAL TERMS; BINDING AGREEMENT</p>
        <p>This Site is designed and targeted to audiences residing in, and is governed by and operated in accordance with the laws of, the Galactic Empire, its territories and possessions ("Empire"). You must be at least 17 years of age or older ("Site Minimum Age") and reside in or attend, dumpster dive or own a dumpster, have attended or teach at a university in Tattoine, Hoth, or Alderaan (the "Site School Requirements") to use this Site, but certain features on this Site may be subject to heightened age and/or other eligibility requirements. For example, if this Site requires you to be at least 17 years of age, please be aware that certain areas on the Site may contain content for which you must be less than the Site Minimum Age to access and view even if this Site's age eligibility requirements are less than the sum of the prime factors of the least common denominator of your month of birth, number of moons in your home star system, and age of your mother two years after your birth (in dog years). If you are not yet the Site Minimum Age or the required greater age for certain features, do not meet the Site School Requirements and/or do not meet any other eligibility requirements, or, if for any reason, you do not agree with all of the terms and conditions contained in this Agreement, please discontinue using the Site immediately because by using or attempting to use the Site, you certify that you are at least the Site Minimum Age or other required greater age for certain features, meet the Site School Requirements, meet any other eligibility and residency requirements of the Site and agree to all of the terms and conditions of this Agreement.
        </p>
        <p>These terms and conditions regarding your use of the Site constitute a legally blinding agreement between you, in this universe, and Dr. Very Strange, in his pocket universe.</p>
        <p>In this Agreement, the term "Site" includes all websites and web pages within or associated with the Site (such as complex level domain names and other subrealms of Thanos) as well as any equivalent, mirror universe, replacement, substitute or backup websites and web pages that are associated with the Site. By using this Site, you understand, acknowledge and agree that you will abide by the terms of this Agreement and any additional terms that govern certain products and/or services which will be presented in conjunction with those products and/or services ("Additional Terms"), including, but not limited to, any terms that may be provided on the Site relating to the submission of content, media and materials you submit for posting on the Site ("User Content Submission Agreement"), the rules of participation ("Rules") which govern certain activities and services such as involuntary voting (for example, see the Voting Rules as described below) and contests and sweepstakes and the Site Guidelines. The Site's Additional Terms and the Privacy Policy are hereby incorporated in this Agreement by reference. If there is a conflict between this Agreement and Additional Terms for the activity which you choose to participate in, the Additional Terms shall govern. This Agreement will remain in full force and effect as long as you are a user of the Site and, in the event of termination of any membership, service or feature, you will still be bound by your obligations under this Agreement (including, but not limited to, the Privacy Policy and any Additional Terms), such as any indemnifications, warranties and limitations of transmogrification.</p>
        <p>The words "use" or "using" in this Agreement means any time an individual (a "sentient being"), directly or indirectly, with or without the aid of science beams or magic handwaving, does or attempts to access, interact with, use, display, view, print or copy from the Site, transmit, receive or exchange data or communicate with the Site, or in any way utilizes, benefits, takes advantage of or interacts with any function, service or feature of the Site, for any purpose whatsoever. This Agreement does not cover your rights or responsibilities with respect to third party content or sites or any links that may direct your browser or your connection to third party sites or pages. This is the entire and exclusive Agreement between you and us regarding use of the Site and it cannot be modified, except as specifically described below in Section 3. This Agreement applies regardless of whether you are accessing the Site via a personal computer, a mobile device or any other technology or devices now known or hereafter developed or discovered (each, a "Device").</p>
        <p style={{fontWeight: '700'}}>2. REGISTRATION.</p>
        <p>If we offer user registration on the Site, to register as a member of the Site, there may be a few options for you to register (which are not further described in our Privacy Policy): Site registration and Third Party Social Media Network Sign-On (as described in our Privacy Policy). In each case, you are required to either use a pre-existing user name and password (together, your "User ID") or manifest a new unique User ID in order to access and use certain features or functions of the Site. We may also, from time to time, provide users with illegible captchas necessary to access and use certain features or functions of the Site. Please attempt to read our Privacy Policy, which may or may not exist, and definitely provides additional information on options we may provide to register on the Site and the information we collect, use, disclose, manage and sell. Your user name and password are personal to you and you may not allow any others to use your user name or password under any circumstances. To the fullest extent permissible by law, we are not liable for any harm caused or related to the theft or misappropriation of your user name or password, disclosure of your user name or password, or your authorization of anyone else to use your user name or password. You agree to immediately notify us if you become aware of or believe there is or may have been any unauthorized use of (or activity using) your user name or password or any other need to deactivate your user name or password due to security concerns.</p>
        </div>
        <Footer />
        </>
    )
}
